package com.business.profiler.exceptions;

public enum ErrorCode {

    INTERNAL_EXCEPTION("500"),
    INPUT_VALIDATION_ERROR("500.1"),
    HTTP_SERVER_EXCEPTION("500.2"),




    NO_PRODUCT_FOUND("400.1"),
    UNABLE_TO_CREATE_PRODUCT("400.2"),
    NO_USER_FOUND("400.3"),
    UNABLE_TO_CREATE_USER("400.4"),
    EXTERNAL_INTEGRATION_ERROR("400.5"),
    REQUEST_DOES_NOT_EXIST("400.6"),
    NO_SUBSCRIPTIONS_FOUND_FOR_USER("400.7"),
    UNABLE_TO_CREATE_SUBSCRIPTION("400.8"),
    ONLY_UPDATE_ACTION_SUPPORTED("400.9"),
    SUBSCRIPTION_ALREADY_EXISTS("400.10"),
    ATLEAST_ONE_SUBSCRIPTION_IS_MANDATORY("400.11"),
    PRODUCT_IS_NOT_ACTIVE("400.12"),
    SUBSCRIPTION_IS_ALREADY_IN_STATUS("400.13"),
    NO_SUBSCRIPTIONS_FOUND_FOR_PRODUCT("400.14"),
    REQUEST_IN_STATUS("400.15"),
    SUBSCRIPTION_STATUS_IS_NULL_OR_EMPTY("400.16"),
    NO_PRODUCTS_FOUND_WITH_STATUS("400.17"),
    NO_REQUESTS_FOUND_WITH_STATUS("400.18"),
    ACKNOWLEDGEMENT_NOT_RECEIVED("400.19");

    private String code;

    ErrorCode(String code){ this.code = code;}

    public String getCode(){ return this.code;}
}
