package com.business.profiler.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Date;

@JsonSerialize
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@DynamoDBTable(tableName = "products")
public class ProductInfo extends BaseModel{

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @JsonProperty("productId")
    private String productId;

    @JsonProperty("productCreatedDate")
    @DynamoDBAttribute
    private Date productCreatedDate;

    @JsonProperty("productStatus")
    @DynamoDBAttribute
    private String productStatus;

    @JsonProperty("productName")
    @DynamoDBAttribute
    private String productName;

    @JsonProperty("productDescription")
    @DynamoDBAttribute
    private String productDescription;

    @JsonProperty("productUrl")
    @DynamoDBAttribute
    private String productUrl;

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public Date getProductCreatedDate() {
        return productCreatedDate;
    }

    public void setProductCreatedDate(Date productCreatedDate) {
        this.productCreatedDate = productCreatedDate;
    }

    public String getProductStatus() {
        return productStatus;
    }

    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductDescription() {
        return productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    public String getProductUrl() {
        return productUrl;
    }

    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }
}
