package com.business.profiler.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

@DynamoDBTable(tableName = "requests")
public class Request extends BaseModel{

    @JsonProperty("userDetails")
    @DynamoDBTypeConverted(converter = UserDetailsTypeConverter.class)
    private UserInfo userDetails;

    @JsonProperty("subscriptionDetails")
    @DynamoDBTypeConverted(converter = SubListTypeConverter.class)
    private List<SubscriptionInfo> subscriptionList;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @JsonProperty("requestId")
    private String requestId;

    @DynamoDBAttribute
    @JsonProperty("requestType")
    private String requestType;

    @JsonProperty("requestStatus")
    private String requestStatus;

    public UserInfo getUserDetails() {
        return userDetails;
    }

    public void setUserDetails(UserInfo userDetails) {
        this.userDetails = userDetails;
    }

    public List<SubscriptionInfo> getSubscriptionList() {
        return subscriptionList;
    }

    public void setSubscriptionList(List<SubscriptionInfo> subscriptionList) {
        this.subscriptionList = subscriptionList;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    public String getRequestStatus() {
        return requestStatus;
    }

    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }
}
